@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package jozufozu.bubbles.content.updrafts;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;