@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package jozufozu.bubbles.client.particles;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;