@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package jozufozu.bubbles.content.stands;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;